# Generated by Django 3.2.7 on 2021-10-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('source', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='videos')),
            ],
        ),
    ]
