# Generated by Django 3.2.7 on 2021-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('codebuild', models.CharField(blank=True, max_length=15, null=True)),
                ('explanation', models.TextField(max_length=250)),
                ('source', models.URLField(blank=True, null=True)),
                ('demo', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artwork')),
            ],
        ),
    ]
