# Generated by Django 3.2.7 on 2021-09-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectitem',
            old_name='codebuild',
            new_name='codebase',
        ),
    ]
