# Generated by Django 5.1.1 on 2025-01-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
